doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    server_version: '5.7'
    charset: utf8mb4
    default_table_options:
      collate: utf8mb4_unicode_ci
    profiling_collect_backtrace: '%kernel.debug%'
    types:
      bookmark_id: 'App\Infrastructure\Doctrine\Type\BookmarkIdType'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/ORM/Mapping'
        prefix: 'App\Domain\Data\Model'
        alias: App
