parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Global
  App\:
    resource: '../src/'

  # Application
  App\Application\API\Action\:
    resource: '../src/Application/API/Action/**/Action.php'
    tags: ['controller.service_arguments']

  # Domain

  # Infrastructure
