parameters:

services:
  _defaults:
    autowire: true

  # Global
  App\:
    resource: '../src/'

  # Application
  App\Application\API\Action\:
    resource: '../src/Application/API/Action/**/Action.php'
    tags: ['controller.service_arguments']

  App\Application\API\Symfony\ArgumentResolver\:
    resource: '../src/Application/API/Symfony/ArgumentResolver/*'
    tags:
      - { name: controller.argument_value_resolver, priority: 255 }

  App\Application\API\Symfony\EventListener\ResponseListener:
    tags:
      - { name: kernel.event_listener, event: kernel.view }
      - { name: kernel.event_listener, event: kernel.exception }

  # Domain
  App\Domain\URIMetadata\URIMetadataReader: '@App\Infrastructure\URIMetadata\OEmbedReader'
  App\Domain\IdGenerator: '@App\Infrastructure\UuidIdGenerator'

  # Infrastructure
