name: CI
on: [push]
jobs:
  build:
    name: Bookmark
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php-version: ['7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, ctype, iconv, intl
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Run PHP CS Fixer
        run: php vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --stop-on-violation --using-cache=no

      - name: Run PHPStan
        run: php vendor/bin/phpstan analyze

      - name: Run PHPUnit - Unit
        run: php vendor/bin/phpunit --testsuite unit

      - name: Run PHPUnit - Func
        run: |
          php bin/console --env=test do:da:dr --if-exists --no-interaction --force
          php bin/console --env=test do:da:cr --if-not-exists --no-interaction
          php bin/console --env=test do:mi:mi --no-interaction
          php vendor/bin/phpunit --testsuite func
