name: CI
on: [push]
jobs:
  build:
    name: Bookmark
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php-version: ['7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: PHP CS Fixer
        run: make php-cs-fixer

      - name: PHPStan
        run: make phpstan

      - name: PHPUnit - Unit
        run: make unit-test

      - name: PHPUnit - Func
        run: make func-test
